### PR TITLE
Changes required for upstream merge

### PR DESCRIPTION
**Pull request by dcadams**
This PR has the changes required for the upstream merge of release-2015-05-18 into edx-platform.

### CODE REVIEW

**Comment by dcadams** [comment]
retest this please

**Comment by dcadams** [comment]
@stvstnfrd would you mind reviewing.

**Comment by stvstnfrd** [comment]
+1

**Comment by dcadams** [comment]
@stvstnfrd  This was what I referred to in planning. This should get merged to master as it's what we're running on prod.

**Comment by stvstnfrd** [comment]
sgtm

**Pull request merged**
