### PR TITLE
WIP: Handle case where there are more than 1 staff step.

### PR DESCRIPTION
**Pull request by dcadams**

### CODE REVIEW

**Comment by stvstnfrd** [comment]
@dcadams Is this to handle the issues we've been seeing occasional with users getting stuck?

**Comment by dcadams** [comment]
Yes, correct. It got held up due to the pain involved in writing a test for ORA2 in general. In fact, this was the reason why my devstack went south.

**Comment by stvstnfrd** [comment]
@dcadams Ever have any luck with this?

**Comment by dcadams** [comment]
Not sure if this is still an issue but would like to keep for a bit.

**Comment by stvstnfrd** [comment]
We can re-open if/when we decide to revisit.

**Pull request closed without merging**
