### PR TITLE
Fix Failing Tests

### PR DESCRIPTION
**Pull request by dcadams**
Fixes 4 failing tests in master.

    Cherry-pick of upstream commit:
    (bb917f6045c04259b2c4ab00e1fc6195d83582b4)

    Four tests were broken due to a hard coded date.

### CODE REVIEW

**Comment by stvstnfrd** [comment]
@dcadams I haven't looked at the upstream ORA2 in a while; is it worth rebasing our (track changes) branch over the most recent upstream/master?

**Comment by stvstnfrd** [comment]
Oh, actually, we did fully fork this so track changes is in our master.

Anyway, is it worth a merge from upstream/master?

**Comment by dcadams** [comment]
@stvstnfrd There are quite a few commits we are lacking from upstream so a merge would be a larger task than this PR given track changes makes quite a few changes. I'll talk to @jinpa about it. Thanks.

**Comment by stvstnfrd** [comment]
@dcadams Yeah, I'm not proposing we shoehorn the merge in here; this just planted the seed for me to ask in general.

**Comment by dcadams** [comment]
@jbau @stvstnfrd now tests have passed on this PR I'd like to either merge this in or a full merge of upstream master. I did try upstream master but had some merge issues that I didn't resolve.

This is a pre-req for my other PR ( Dcadams/ora grade override origin #7 ).

**Comment by stvstnfrd** [comment]
+1 to cherry-pick this and defer merge of upstream/master.

We should aim to merge upstream/master when we merge the platform named release.

**Pull request merged**
